services:
  postgres:
    image: postgres:18
    container_name: conectalocal_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: conectalocal_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: conectalocal_backend
    restart: always
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      DB_USER: postgres
      DB_PASSWORD: 12345
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: conectalocal_db
      PORT: 3000
      JWT_SECRET: mi_clave_secreta_para_conectalocal_2026

volumes:
  postgres_data: