name: ConectaLocal CI Pipeline

on:
  push:
    branches: [ "main", "develop" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: 1. Descargar el código
      uses: actions/checkout@v3

    - name: 2. Preparar Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: 3. Instalar dependencias
      run: npm install

    - name: 4. Correr las pruebas (Jest)
      run: npm test -- --coverage